import type { Metadata } from "next";
import { Alegreya } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";

const alegreya = Alegreya({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alegreya.className} antialiased relative `}>
        <Nav />
        {children}
        </body>
    </html>
  );
}
